#启动环境选择的配置
spring:
  profiles:
    active: dev   # 设置默认是dev
---
server:
  port: 7001
#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-dev

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureaka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果fetch-registry为false，则表示自己为注册中心
    service-url: #监控页面
      #单机：点进去参考源码，可看到默认的url端口配置为8761，我们设置为自己的端口。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

      #集群（除自身外 关联其他所有）
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7001
#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-test

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureaka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果fetch-registry为false，则表示自己为注册中心
    service-url: #监控页面
      #单机：点进去参考源码，可看到默认的url端口配置为8761，我们设置为自己的端口。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

      #集群（除自身外 关联其他所有）
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
