# 启动环境选择的配置
spring:
  profiles:
    active: dev

# springboot启动多环境的配置
---
server:
  port: 8201

# spring的配置
spring:
  profiles: dev
  application: 
    name: springcloud-config-client-dev

# Eureka的配置. 服务注册到Eureka中, 需要一个路径地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8202
# spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-client-test

# Eureka的配置. 服务注册到Eureka中, 需要一个路径地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/